version: "3"
services:
 vampi-secure:
  build: ./
  image: mathersb2j/vampi-secure:latest
  container_name: vampi-secure
  ports:
   - 5001:5000
  environment:
   - vulnerable=0

 vampi-vulnerable:
  build: ./
  image: mathersb2j/vampi-vulnerable:latest
  container_name: vampi-vulnerable
  ports:
   - 5000:5000
  environment:
   - vulnerable=1
