version: "3"
services:
 vampi-secure:
  image: fxlabs/vampi_docker:latest
  container_name: vampi-secure
  ports:
   - 5001:5000
  environment:
   - vulnerable=0
   - tokentimetolive=300

 vampi-vulnerable:
  image: fxlabs/vampi_docker:latest
  container_name: vampi-vulnerable
  ports:
   - 5002:5000
  environment:
   - vulnerable=1
   - tokentimetolive=300
