version: 2.1

env:
  ACTIVE_API_URL: "<ACTIVE_API_URL>"
  ACTIVE_REGISTRY_URL: "<ACTIVE_REGISTRY_URL>"
  ACTIVE_BACKEND_URI: "<ACTIVE_BACKEND_URI>"

jobs:
  scan:
    docker:
      - image: cimg/base:stable 
    steps:
      - checkout

      # Start your local server
      - run:
          name: Start Local Server
          command: |
            docker-compose -f docker-compose.yml up -d

      # Docker login
      - run:
          name: Docker Login
          command: |
            echo $ACTIVE_REGISTRY_PASSWORD | docker login $ACTIVE_REGISTRY_URL -u $ACTIVE_REGISTRY_USER --password-stdin

      # Run Active Testing Scan
      - run:
          name: Active Testing Scan
          command: |
            docker run \
              --add-host=host.docker.internal:host-gateway \
              -e ACTIVE_CONFIG_FILE_PATH=<PATH_TO_ACTIVE_CONFIG_FILE> \
              -e ACTIVE_BACKEND_URI=$ACTIVE_BACKEND_URI \
              -v $(pwd)/noname:<ACTIVE_CONFIG_FILE_DIR> \
              $ACTIVE_REGISTRY_URL/active-cli:$(curl -k $ACTIVE_API_URL/backend/version) scan \
              --api-url=$ACTIVE_API_URL \
              --api-token=$ACTIVE_API_TOKEN \
              --test-group-id=<TEST_GROUP_ID> \
              --branch-name=$CIRCLE_BRANCH \
              --severity-threshold=<SEVERITY_THRESHOLD>

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Deploy
          command: echo "Security scan passed, deploying to production"

workflows:
  version: 2
  scan_and_deploy:
    jobs:
      - scan
      - deploy:
          requires:
            - scan
