name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pullrequest:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Run Prisma Cloud Scan
        id: prisma-cloud
        uses: bridgecrewio/checkov-action@master 
        env:
          PRISMA_API_URL: https://api4.prismacloud.io
        with:
          api-key: ${{ secrets.BC_API_KEY }}
          use_enforcement_rules: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build secure docker image
      #   run: docker build -t mathersb2j/vampi-secure:latest .
      # - name: Push secure image to docker hub
      #   run: docker push mathersb2j/vampi-secure:latest
      
      - name: Build vulnerable docker image
        run: docker build -t mathersb2j/vampi-vulnerable:latest .
      - name: Push vulnerable image to docker hub
        run: docker push mathersb2j/vampi-vulnerable:latest

  deployment:
    needs: build
    runs-on: self-hosted
    steps:
      # - name: Pull secure image
      #   run: docker pull mathersb2j/vampi-secure:latest
      - name: Pull vulnerable image
        run: docker pull mathersb2j/vampi-vulnerable:latest
      # - name: Delete old secure container
      #   run: docker rm -f vampi-secure
      - name: Delete old vulnerable container
        run: docker rm -f vampi-vulnerable
      # - name: Run secure docker container
      #   run: docker run -d -p 5000:5000 --name vampi-secure mathersb2j/vampi-secure:latest
      - name: Run vulnerable docker container
        run: docker run -u root:root -d -p 5000:5000 --name vampi-vulnerable mathersb2j/vampi-vulnerable:latest


