name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout source
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vampi:latest
          platforms: linux/amd64,linux/arm64

  deployment:
    runs-on: self-hosted
    steps:
      - name: Pull secure image
        run: docker pull mathersb2j/vampi-secure:latest
      - name: Pull vulnerable image
        run: mathersb2j/vampi-vulnerable:latest
      - name: Delete old secure container
        run: docker rm -f vampi-secure
      - name: Delete old vulnerable container
        run: docker rm -f vampi-vulnerable
      - name: Run secure docker container
        run: docker run -d -p 5000:5000 --name vampi-secure mathersb2j/vampi-secure:latest
      - name: Run vulnerable docker container
        run: docker run -d -p 5000:5000 --name vampi-vulnerable mathersb2j/vampi-vulnerable:latest


